### ISSUE TITLE
deploy storybook + browser lib

### ISSUE THREAD

**Issue by MortenHofft** [gbif/gbif-web#10]
It would be useful to deploy the browser build of the react components along with graphql and the ES API.
This would ensure that the used widget version is the same as graphql etc.

perhaps `react-components.gbif-*.org` ?

It needs to be build using `npm run build-client` and the folder to serve is `/dist`

**Background**
Currently the hosted portals use a cdn pointing to github to get the react components. But that version might not have been deployed (meaning it might assume a different graphql schema).
That could also mean that our storybook was made available online.

It would be nice to add a noindex http header to it all (similar to https://github.com/gbif/hosted-portals/issues/14). The storybook is not really something we want to advertise as such.

**Comment by MattBlissett** [comment]
This is complete, except for needing a release to deploy it to react-components.gbif.org for the first time.
