### ISSUE TITLE
Coordinate uncertainty regex doesn't cover range for term

### ISSUE THREAD

**Issue by tucotuco** [gbif/gbif-web#17]
Real values of coordinateUncertaintyInMeters can't be outside the range [1, 20037509] (see https://github.com/tdwg/bdq/issues/109).

The regex at 
https://github.com/gbif/gbif-web/blob/b2ff47f6006e93c3c89f8def3db030e883548084/packages/react-components/src/utils/filterBuilder/commonFilters.js#L300

doesn't reflect this.

**Comment by tucotuco** [comment]
Rather than make separate issues for all of these, here are more regex expression that should be reviewed:

Elevation (https://github.com/tdwg/bdq/issues/112): [-430,8850]
Depth (https://github.com/tdwg/bdq/issues/187): [0,11000]

**Comment by MortenHofft** [comment]
There are many records that fall outside those intervals. For simplicity and to reflect actual usage then I'm in favour of keeping the range of allowed values very open. The regex should ideally ensure that it is syntactic correct, but meaningless intervals are allowed.

Here is 7500 records that has an elevation above 10km
https://www.gbif.org/occurrence/search?elevation=10000,*&advanced=1&occurrence_status=present

That isn't to say that the elevation is correct, but I'm reluctant to restrict this. Especially if it isn't restricted in the data.

See also https://github.com/gbif/portal-feedback/issues/3407

**Comment by tucotuco** [comment]
I agree, one should be able to search on bad data. What was I thinking? Thanks.
