### ISSUE TITLE
Charting library

### ISSUE THREAD

**Issue by MortenHofft** [gbif/gbif-web#178]
It would be good to find a charting library soon. I'm not really wedded to anything in particular. My main criteria would be that it:
* can be styled
* that it isn't a huge bundle
* that it supports the chart types we need (not really clear what those are)
* that it is possible to add events, attach hooks, custom tooltips and such. 
* It should have an export feature - that is a recurrent request. 
* And it should be possible to translate values (months, download options etc)

**Highcharts**
On GBIF.org we have been using [highcharts](https://www.highcharts.com/) - that was largely decided by someone else on the team having used it in the past and enjoyed it.
* when we evaluated the license back then, the conclusion was that it was free for us given that we are not a for profit organisation https://www.highcharts.com/forum/viewtopic.php?t=45225 (the only link I can find just now - I believe we also has a mail thread somewhere)
* It isn't the prettiest I find, but it does allow some degree of styling.
* I remember it as being flexible and okay to work with.
It has served us well I find. 

**Vega-lite**
Suggested in https://github.com/gbif/analytics/issues/13
It is 2 years ago, but back then my conclussion was that it was a large bundle with no support for custom click events. But that might have changed during the last 2 years

**Some name**
Our designer @javiesgm had a suggestion for one he liked, but I cannot remember the name not find it in any thread or issues, not do I remember the conclusion if any.
UPDATE: I still do not remember the name, but I now remember the conclusion: it was intended for print media and had no concept of click events and such.

**Comment by MortenHofft** [comment]
*Apexcharts*
@jack-brinkman suggested this. I do not know it, but the bundle size looks fine if [bundlephobia](https://bundlephobia.com/package/apexcharts@3.35.5 ) is to be trusted.

**Comment by MortenHofft** [comment]
**Observable Plot**
https://github.com/observablehq/plot
@thomasstjerne suggests this one as being nice to work with.

**Comment by jack-brinkman** [comment]
As per discussions with @MortenHofft, here's a review of several charting libraries:

| Library                                                                                        | Styling                                                                                                                                 | Bundlephobia                                                                                                                                                                                                                                                                          | Chart Types                                                                | Custom Events/Hooks/Tooltips                                                           | Localisation                                                         | Exporting                                                             |
|------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------|----------------------------------------------------------------------------------------|----------------------------------------------------------------------|-----------------------------------------------------------------------|
| [ApexCharts](https://apexcharts.com/)                                                          | [Yes](https://apexcharts.com/docs/colors)                                                                                               | **ApexCharts:** [490.4kB, 126.2kB (gzip)](https://bundlephobia.com/package/apexcharts@3.36.3)<br/>**react-apexcharts:** [4.8kB, 1.9kB (gzip)](https://bundlephobia.com/package/react-apexcharts@1.4.0)                                                                                | [14](https://apexcharts.com/docs/chart-types/line-chart/) (No Sunburst)    | [Yes](https://apexcharts.com/docs/events/)                                             | [Yes](https://apexcharts.com/docs/localization/)                     | [Yes](https://apexcharts.com/docs/options/chart/toolbar/)             |
| [vega-lite](https://vega.github.io/vega-lite/)                                                 | [Yes](https://vega.github.io/vega-lite/docs/config.html)                                                                                | **vega-lite:** [301.3kB, 90.9kB (gzip)](https://bundlephobia.com/package/vega-lite@5.6.0)<br/>**vega-embed:** [74.1kB, 24.2kB](https://bundlephobia.com/package/vega-embed@6.21.0)<br/>**react-vega-lite:** [51.4kB, 16.6kB](https://bundlephobia.com/package/react-vega-lite@6.1.0)  | [Lots](https://vega.github.io/vega-lite/examples/) (Sunburst only in Vega) | [Yes](https://vega.github.io/vega/docs/event-streams/)                                 | Only in [Vega](https://vega.github.io/vega/docs/api/locale/)         | [Not easily](https://vega.github.io/vega-lite/tutorials/figures.html) |
| [react-chartjs-2](https://react-chartjs-2.js.org/) (uses [chart.js](https://www.chartjs.org/)) | [Yes](https://www.chartjs.org/docs/3.2.1/axes/styling.html)<br/>Also see [here](https://www.chartjs.org/docs/3.2.1/general/colors.html) | **react-chartjs-2:** [Broken](https://bundlephobia.com/package/react-chartjs-2)<br/>**chart.js** [192.8kB, 66kB (gzip)](https://bundlephobia.com/package/chart.js@4.0.1)                                                                                                              | [9](https://react-chartjs-2.js.org/components) (No Sunburst)               | [Yes](https://www.chartjs.org/docs/latest/configuration/interactions.html)             | [Yes](https://www.chartjs.org/docs/latest/configuration/locale.html) | No                                                                    |
| [recharts](https://recharts.org/en-US)                                                         | [Yes](https://recharts.org/en-US/guide/customize)                                                                                       | [487.1kB, 122.1kB](https://bundlephobia.com/package/recharts@2.1.16)                                                                                                                                                                                                                  | [11](https://recharts.org/en-US/api)                                       | [Partial](https://recharts.org/en-US/api)<br/>Basic events/hooks, customisable tooltip | No                                                                   | No                                                                    |
| [Victory](https://formidable.com/open-source/victory/)                                         | [Yes](https://formidable.com/open-source/victory/guides/themes)                                                                         | [663.9kB, 151.1kB](https://bundlephobia.com/package/victory@36.6.8)                                                                                                                                                                                                                   | [15](https://formidable.com/open-source/victory/docs/victory-box-plot)     | [Yes](https://formidable.com/open-source/victory/guides/events/)                       | No                                                                   | No                                                                    |

**Comment by MortenHofft** [comment]
I'm okay with trying to use ApexCharts and learn more about how well it works for us. Worst case we change library for a few components

**Comment by MortenHofft** [comment]
Another missing type seem to be nested tree maps (if that is the correct term) - it is another popular visualization (requested again here https://github.com/gbif/portal-feedback/issues/4452#issuecomment-1335302288)

<img width="607" alt="Screenshot 2022-12-05 at 10 17 47" src="https://user-images.githubusercontent.com/6759267/205600208-a147a7ca-9413-4396-9e12-ced1c5066e40.png">
<img width="609" alt="Screenshot 2022-12-05 at 10 17 52" src="https://user-images.githubusercontent.com/6759267/205600213-474febd7-6e82-44cd-849a-a8b3fd7b5221.png">

**Comment by MortenHofft** [comment]
I would say this is the list of most important charts

* horisontal and vertical bar charts
* Sunbursts
* Nested tree maps
* Line charts
* Pies - could be replaced by a chart, but people like them and variation is nice
* Heatmaps for multi dimensional charts

Would be nice to have
* spark lines
* donuts
* bubbles - we never used them in the past but I could imagine it could happen

**Comment by MortenHofft** [comment]
@jack-brinkman I'm curious to know why Highcharts doesn't appeal to you. I must admit that it is the most attractive one to me. It isn't as pretty, but it is smaller and versatile and meets all formal criteria. And can be styled. Perhaps also to be prettier. The main caveat aside from styling is that the license requires more consideration (ensure that it is still free for non profit)

**Comment by MortenHofft** [comment]
@javiesgm how do you as a designer feel about the look of [highcharts](https://www.highcharts.com/demo) - personally I find that it looks less nice than the others that @jack-brinkman mentions.

It is what we currently use on GBIF.org. We have done a bit of styling to it, but not much.

ApexCharts seem nicer to work with from first glance. But I still gravitate towards Highcharts myself, simply because it supports more charts (smaller is nice of course, but matters less when the difference is so small)

**Comment by djtfmartin** [comment]
@MortenHofft I think licensing for highcharts might be an issue for ALA. I can check, but i dont think we qualify as a not for profit.

**Comment by javiesgm** [comment]
Apexcharts does look prettier, and at first glance, I'd say it would require less styling effort (my main concern). But I agree with Morten that sticking with Highcharts may be the best option in the long run. I like that it offers more visualization options within the same library. Having experience using them is a plus too. And the one I like is this one https://www.rawgraphs.io, but it certainly falls behind in terms of the requirements discussed here.

**Comment by MortenHofft** [comment]
I believe the issue with https://www.rawgraphs.io/ is that it isn't really intended for web, but for print. At least here examples are mostly print. And I haven't been able to find any documentation related to event handling (click, hover and such)

**Comment by MortenHofft** [comment]
It also seems obvious to look into the presumably many d3 based chart libraries since we already use d3 to visualise clusters https://hp-theme.gbif-staging.org/occurrence/search?view=CLUSTERS

**Comment by jack-brinkman** [comment]
@MortenHofft I'm not opposed to Highcharts if it meets your requirements & it's the direction you're keen to head in :)

As you and @djtfmartin have already noted, the only real issue is the licensing. I agree that importing several other charting components/libraries is not a very nice solution, so if Highcharts includes everything you need, I'm happy to go with it. I'm also not too concerned with styling - as you've mentioned, we can customise it to look a bit cleaner & nicer.

**Comment by MortenHofft** [comment]
We went with highcharts in the end.
