### ISSUE TITLE
Get events explorer into gbif-web master branch

### ISSUE THREAD

**Issue by MortenHofft** [gbif/gbif-web#186]
This work has been started in https://github.com/gbif/gbif-web/issues/174
But there are still tasks left. 

* the refactored graphql branch (https://github.com/gbif/gbif-web/issues/174) need to be merged with master.
* We should add two set of occurrence configurations in the es-api. One for events and another for occurrences as they appear in hosted portals already. This is because GBIF isn't ready to use the events index yet. And will continue to have occurrences in a separate index with a slightly different schema (not nested).
* And then we should move the endpoints in https://github.com/gbif/graphql-events into `gbif-web/graphql-api`
* And them make it configurable which graphql types is exposed based on config (GBIF wouldn't support type events to begin with, and ALA would not support e.g. nodes)

**Comment by jack-brinkman** [comment]
The following tasks are addressed in the `joins-modular` branch:
- The endpoints from https://github.com/gbif/graphql-events have been moved into `gbif-web/graphql-api` (920e1f031ab42454c9b821d99d12ad2163b2e134)
- The GraphQL types that are exposed are configurable (4359d4305791992e46f8b5d0028aafa2902cdc11)

**Comment by djtfmartin** [comment]
i think this is done thanks to @MortenHofft
