### ISSUE TITLE
Make labelMaker fallback to 'id' prop on error state

### ISSUE THREAD

**Issue by jack-brinkman** [gbif/gbif-web#200]
Labels produced by `labelMaker` display 'unknown' when an error occurs. It might be more helpful if the user is shown the `id` prop instead. For instance, if a 'Trial' event is selected using the filter button since there's no corresponding GBIF vocabulary for that event type, the error label is shown, rather than the 'Trial' label:

![image](https://user-images.githubusercontent.com/104949733/202085678-2f83232c-41b9-42b0-82a8-3d0e6c039622.png)

**Comment by jack-brinkman** [comment]
New filter button with `id` prop fallback:

![image](https://user-images.githubusercontent.com/104949733/202086508-0646e2e6-90f3-4cc1-b830-d84eb9349eef.png)

**Comment by MortenHofft** [comment]
Sounds to me like we should update the vocabulary instead? Having a fallback to the value mostly just masks the error as I understand it - leaving the issue that translations wont work and that we have an unwanted discrepancy between our APIs.

It you really want a label that just takes the verbatim values, then it is possible to overwrite the label to show a formatted version of the value - could be an identity function. But it sounds like something we should solve at a different level?

**Comment by djtfmartin** [comment]
I think the reality is we are some way away from having a mature stable vocab for event types (as much as we'd like one / need one).

**Comment by MortenHofft** [comment]
In that case I'd rather we created a custom label type for this, rather than changing behaviour for all labels.

**Comment by MortenHofft** [comment]
If there is no useful vocabulary then I'm fine with removing that from the filter configuration. Is that the case @djtfmartin ?

**Comment by djtfmartin** [comment]
The vocab is incomplete / WIP. Im also not clear how easily it will be to get a published version of it into the GBIF prod registry.

**Comment by MortenHofft** [comment]
Let us just remove it from the filter then and use the raw values
