### ISSUE TITLE
Error boundaries

### ISSUE THREAD

**Issue by jack-brinkman** [gbif/gbif-web#206]
Error boundaries would be a nice addition to the library (for the larger search components) - it would prevent rendering bugs from crashing the entire portal. One could be added to the `PredicateDataFetcher` component to handle view-specific errors  (i.e. #198) with the rest of the application remaining functional.

**Comment by jack-brinkman** [comment]
@MortenHofft @djtfmartin This is my first-pass implementation of the `ErrorBoundary` component. It currently wraps the `PredicateDataFetcher` component to handle view-specific errors. The `Report issue` button redirects the user to create a new GitHub issue in this repo, and the 'Hide details' toggles the error stack trace. I've also added locale support.

Screenshot:

![image](https://user-images.githubusercontent.com/104949733/203450993-60624e10-bb16-4d1e-8d94-a31d280a11b5.png)

**Comment by MortenHofft** [comment]
I get below error: do you have something set up locally perhaps that mask this?
```
Uncaught ReferenceError: React is not defined
    at ./src/components/ErrorBoundary/ErrorBoundary.js 
```

**Comment by MortenHofft** [comment]
If I add a deliberate typo in the qraphql query, then this is not triggered (instead I simply see the `failed to fetch data`  placeholder). Which makes sense given how it is implemented, but it would be nice if the end result for the user was the same or similar.

**Comment by jack-brinkman** [comment]
Are you receiving the error in storybook? If so, that's my bad - I forgot that it requires an explicit React import to run the components, I'll commit a fix. I'll also look into re-throwing callback errors so they still trigger the error boundary 👍

**Comment by MortenHofft** [comment]
I just writing comments here as I test this.
For the hide/show. I'm not sure how much value I think that has. Especially not as my choice isn't stored but reset on every new error I see. So I see the error details on any new error anyway. Perhaps it would make better sense to hide per default?

Also it would be nice to include the error message in the github link? `issue/new?title=something&body=something`

**Comment by MortenHofft** [comment]
I'm not entirely sure, but I wonder if it would make more sense to include this on something less generic than the `dataPredicateFetcher` which is intended as a generic component that, in theory, might as well be used for a small section with a table on any page - and hence the error component is likely to look different. And instead have it on the `list` and `table`. Or perhaps even on the `EventSearchPageLayout` instead, which would handle it for datasets/events/sites/map/download in one go?

**Comment by MortenHofft** [comment]
I've forked your branch @jack-brinkman and changed the UI a bit. And added some templating to the issue

<img width="880" alt="Screenshot 2022-11-23 at 16 09 04" src="https://user-images.githubusercontent.com/6759267/203580989-94f60ff8-24b5-494a-aec5-1d942f6b5049.png">

------
Thank you for reporting this issue. Please describe what happened.




**Error message for diagnostics**
```
TypeError: Cannot read properties of null (reading 'join')
    at List (http://localhost:6006/main.82c50d66651f5cf41219.hot-update.js:146:5)
    at renderWithHooks (http://localhost:6006/vendors~main.iframe.bundle.js:189246:18)
    at mountIndeterminateComponent (http://localhost:6006/vendors~main.iframe.bundle.js:192072:13)
    at beginWork (http://localhost:6006/vendors~main.iframe.bundle.js:193310:16)
    at HTMLUnknownElement.callCallback (http://localhost:6006/vendors~main.iframe.bundle.js:178206:14)
    at Object.invokeGuardedCallbackDev (http://localhost:6006/vendors~main.iframe.bundle.js:178255:16)
    at invokeGuardedCallback (http://localhost:6006/vendors~main.iframe.bundle.js:178317:31)
    at beginWork$1 (http://localhost:6006/vendors~main.iframe.bundle.js:198220:7)
    at performUnitOfWork (http://localhost:6006/vendors~main.iframe.bundle.js:197032:12)
    at workLoopSync (http://localhost:6006/vendors~main.iframe.bundle.js:196963:5)
```
Location: http://localhost:6006/iframe.html?id=search-ala-eventsearch--example&viewMode=story&args=

**Comment by jack-brinkman** [comment]
That looks great @MortenHofft! I agree with hiding the error details by default. If `PredicateDataFetcher` is intended to be used in smaller sections of the page, then yes, I agree that it should be moved to a less generic component.

However, if the Error Boundary were moved to wrap the tab views within the `EventSearchPageLayout` component, if a view were to error, the other views would become inaccessible as the boundary still wraps the whole view area. One workaround would be to update the `tabComponents` object to include both tab & view elements, like so:

```javascript
const tabComponents = {
  DATASETS: {
    tab: <NavItem key={`DATASETS_TAB`} label={<FormattedMessage id="search.tabs.datasets" defaultMessage="Datasets"/>} data-targetid="datasets" onClick={e => setActiveView('DATASETS')} isActive={activeView === 'DATASETS'} />,
    view: <List />
  },
  EVENTS: {
    tab: <NavItem key={`EVENTS_TAB`} label={<FormattedMessage id="search.tabs.events" defaultMessage="Events"/>} data-targetid="events" onClick={e => setActiveView('EVENTS')} isActive={activeView === 'EVENTS'} />,
    view: <Table />
  },
  // ... the rest
}

// we also need to make a slight change to the tab rendering:
<NavBar style={{ marginLeft: 10 }}>
  {tabs.map(tab => tabComponents[tab].tab)}
</NavBar>
```

Then, we can wrap each active view in an error boundary & maintain the functionality of the other views in the app.

```javascript
<div css={cssViewArea({ theme })}>
  {Object.entries(tabComponents).map(([tab, { view }]) =>
    tab === activeView && <ErrorBoundary>{view}</ErrorBoundary>
  )}
</div>
```

An error boundary could also be added to the `StandardSearch` component to handle errors at a higher level for _all_ of the search components (`Dataset`, `Collection`, `Institution`, etc.).

**Comment by jack-brinkman** [comment]
Re. using the error boundaries for GraphQL-related errors: Perhaps we could add a prop/flag to `PredicateDataFetcher` (i.e. `throwGraphErrors`) & `useQuery` and enable it for the views you wish to use the error boundary in:

```javascript
const { data, error, loading, load } = useQuery(DOWNLOADS, { lazyLoad: false, throwGraphErrors: true });
```
```javascript
function Table() {
  return <PredicateDataFetcher
    graphQuery={QUERY}
    throwGraphErrors // here
    ...props
  />
}
```

It might also be nice to throw the actual GraphQL error rather than just displaying 'Network Error', so we get some more descriptive information. Something like this (I'm using the current `feature/error-boundaries` branch as I didn't want to mess with your styling one):

![image](https://user-images.githubusercontent.com/104949733/203669222-8758faf8-3b4a-4ffb-a243-81845e9dd112.png)

**Comment by MortenHofft** [comment]
Thanks jack. Yeah I suspected it didn't make sense to wrap them as a whole without having a way to invalidate the error. Wrapping the views individually makes more sense to me. Even if it is a bit repetitious. 

Just thinking out loud, I wonder if it would make sense to have an `invalidateOn` prop on the error boundary.
```
//Layout
<ErrorBoundary invalidateOn={activeView}>
  {activeView === 'DATASETS' && <List />}
  {activeView === 'EVENTS' && <Table />}
  {activeView === 'SITES' && <Sites />}
  {activeView === 'MAP' && <Map />}
  {activeView === 'DOWNLOAD' && <Download />}
</ErrorBoundary>

//ErrorBoundary
componentDidUpdate(prevProps) {
  if (prevProps.invalidateOn !== this.props.invalidateOn) {
    this.setState({
      ...this.state,
      error: false
    });
  }
}
```

**Comment by MortenHofft** [comment]
Just to capture our discussion earlier @jack-brinkman 

The `throwGraphErrors` part we will roll back. The reasoning being that GraphQL errors come in so many flavours that handling them all the same is unlikely. It could be a minor error such as a single field or a small section of the page that won't load due ti a timeout, or it could be the core entity that fails. Only the latter example will probably trigger a full page error.

Secondly we decided to opt for the explicit, and fairly simple version of letting each view handle their own error boundary. It is explicit and simple. So adding `<ErrorBoundary>` as a wrapper on e.g. the `List/index.js` https://github.com/gbif/gbif-web/blob/master/packages/react-components/src/search/EventSearch/views/List/index.js#L154

**Comment by MortenHofft** [comment]
@jack-brinkman I've added the useQuery feature to have it throws errors as you had done in https://github.com/gbif/gbif-web/commit/b3c3930a9f00d2f169b0fe5bb56e1d6bb104a65f
It made good sense to me to have it as an option. But I've split it into 2, networks errors and anyError.

**Comment by jack-brinkman** [comment]
@MortenHofft Fantastic! Thanks for capturing that. That sounds good to me.

**Comment by jack-brinkman** [comment]
Reverted commits for branch parity with **[feature/error-boundaries-styling](https://github.com/gbif/gbif-web/tree/feature/error-boundaries-styling)**, as Morten is implementing the discussed changes.
