### ISSUE TITLE
Querying Occurrences from Events

### ISSUE THREAD

**Issue by jack-brinkman** [gbif/gbif-web#211]
Being able to query the occurrences related to a specific event would be a helpful addition.

**Comment by MortenHofft** [comment]
That should already be possible by using an `occurrenceSearch` query with a filter for a dataset and eventId. But that is awkward for ALA as you do not map the occurrences. 

It is also an option to add an `occurrences` field on the event type that expose all of the occurrence search functionalities, it is a bit more dangerous as it then allows very expensive queries (give me 100 events and for each trigger an occurrence search). So I'm a bit more dubious about that approach. And it would result in the same issues for ALA as it would expose dataset, publisher, collection, institution types again.

**Comment by jack-brinkman** [comment]
Closing in favour of #217 for now
