### ISSUE TITLE
relatedTaxa field on EventType

### ISSUE THREAD

**Issue by jack-brinkman** [gbif/gbif-web#217]
One purpose behind #211 was to enable the querying of taxonomic data related to events. After some thought, although it would be great to make the ALA Collectory interoperable with the GBIF GraphQL types (enabling ALA to implement GBIF's `Occurrence` type properly/fully - #205), a more straightforward short-term solution would be to add a `relatedTaxa` field on the `Event` GraphQL type. Something akin to the following schema (a modified version of one that @MortenHofft provided):

```
type RelatedTaxon {
  acceptedTaxonKey: Int!
  species: String
  speciesKey: String
  infraspecificEpithet: String
}

type Event {
  ...
  relatedTaxa: [RelatedTaxon]!
}
```

**Comment by MortenHofft** [comment]
Could you expand on what `relatedTaxa` is (how do we get them)

* is it occurrences attached to the event?
* is it unique taxa (leaf only, or higher taxonomy as well?) of the occurrences attached to the event
* Is it related taxa for this event or also its child events?
* Is it only species (I ask because it says speciesKey).
* Is absences included?

I believe this is related to below issue, the comment might be relevant here as well:
https://github.com/gbif/gbif-web/issues/213#issuecomment-1328797044

**Comment by MortenHofft** [comment]
@jack-brinkman are you sure this works, it looks to me like you are using occurrence documents to fill the information from the facets. Without doing any new queries. 
So get facets
https://github.com/gbif/gbif-web/commit/af26f7c1e1a77af14a48c7bd3dfc4f4ddc826d30#diff-e3e534e63f59aa39860496c6983699585166d829be09533176c133b5cd3c70e1R168

and then fill the kingdom, phylum etc using the documents that happened to have returned along with the facets (20 results or so)
https://github.com/gbif/gbif-web/commit/af26f7c1e1a77af14a48c7bd3dfc4f4ddc826d30#diff-71ff7bcb282a75b1cbaa4569d8c74d8ecef277e03521a53160f0caf933fe9106R1

**Comment by jack-brinkman** [comment]
@MortenHofft Ah - right. I was trying to avoid the need for an extra query by using the existing occurrence documents; however, if only 20 occurrence documents are returned & there's no guarantee they'll hold all of the needed taxonomic information, then more queries it is :)

**Comment by MortenHofft** [comment]
You can change the limit to something higher and the individual results do hold the necessary information, but...

Each event can have thousands of occurrences or more. So unless you ask for ALL occurrences for an eventId, then there is no guarentee that the occurrences will contain the document you need to expand the keys you get back in facets. Say: 1000 occurrences, representing 2 taxa. 1 gorilla, 999 roses. The facets will return rose: 999, gorilla: 1. But unless you also ask for all 1000 documents, you might not have the gorilla occurrence information available.

If performance becomes an issue, then we can look into a custom endpoint on es-api that use ES to have a nested aggregation where it returns the first document for each facet result. that might perform better.

But for now I believe the simplest would be to simply trigger a new query per facet key. Essentially a species lookup per key.

**Comment by MortenHofft** [comment]
I tend to think we should split the resolver into a GBIF and an ALA one. The reasoning being that it is sort of a hack to use the occurrence API to fetch this information. A species datasource is really the natural (and fastest) endpoint for this.
ALA might decide to mimic that using the occurrence data, but I believe the proper thing would be to use a species endpoint

**Comment by jack-brinkman** [comment]
A final summary of this change: a new `distinctTaxa` field has been added to the GraphQL `Event` type, which returns taxonomic information about the **distinct accepted** taxa of an event (via the `gbifClassification_acceptedUsage_key` facet).


```graphql
type Event {
  eventID: String
  ...
  distinctTaxa: [DistinctTaxon]!
}

type DistinctTaxon {
  count: Int
  taxonKey: String
  taxonRank: String
  scientificName: String
  kingdom: String
  kingdomKey: String
  phylum: String
  phylumKey: String
  class: String
  classKey: String
  order: String
  orderKey: String
  family: String
  familyKey: String
  genus: String
  genusKey: String
  species: String
  speciesKey: String
}
```

The taxonomic information for each taxon key is retrieved via the [taxon data source](https://github.com/gbif/gbif-web/commit/eacfe38b43fb9e3b054586b7e8c08c029db84f5e#diff-3f5550991e0e49375edd0efbb68bc08ce57145b69ddbb0caff19499a13625ac1) using the ALA BIE API ([example query](https://bie-ws.ala.org.au/ws/species/https://id.biodiversity.org.au/taxon/apni/51286863.json)).

**Comment by MortenHofft** [comment]
Looks great. Thank you. As a last minute change: could we rename `taxonKey` to `key`. this is just in the interest of having it the same as the existing taxon type
