### ISSUE TITLE
Search event occurences for distinct terminal taxa

### ISSUE THREAD

**Issue by MortenHofft** [gbif/gbif-web#225]
@jack-brinkman need a list of distinct terminal taxa.

Aggregations per speciesKey will miss out distinct occurrences that is only determined to genus.
Aggregations per taxonKey will include the full classification, so that e.g. plantae will be included, despite no occurrences is only determined to the kingdom level.

I would think that `gbifClassification.acceptedUsage.key` could be used. It will ignore synonyms. 
So a list of occurrences like this simplified taxonomy:
occurrence1: animal mammal lion
occurrence2: animal mammal

facet on speciesKey: [lion: 1]
facet on taxonKey: [animal: 2, mammal: 2, lion: 1]
facet on acceptedUsage: [lion: 1, mammal: 1]

So @jack-brinkman I think you should be able to use `gbifClassification_acceptedUsage_key`

https://aws-events-es-2022.ala.org.au/es/event-occurrence?apiKey=your-api-key&facet=gbifClassification_acceptedUsage_key&size=0

EXCEPT: it currently use the `key` not the `guid`. @djtfmartin is the ambition that GBIF and ALA align on this? Couldn't we make the key field a string in the schema and use that?

**Comment by djtfmartin** [comment]
@MortenHofft we could, we should :)
Related issue: https://github.com/gbif/pipelines/issues/765

**Comment by MortenHofft** [comment]
How about changing the key to a keyword then and populate that instead of the current `guid` field.

**Comment by djtfmartin** [comment]
Unfortunately https://github.com/gbif/pipelines/issues/765 needs to be addressed first as this is defined in the common AVRO schemas (which we don't want to fork).

**Comment by MortenHofft** [comment]
How about we change the es-api for `event-occurrence` to use the `guid` then? but keep the name - that way there will be no changes as far as GraphQL is concerned. ALA have use for it now, and we all agree it should be changed.

**Comment by djtfmartin** [comment]
Sounds good to me.

the kingdomKey and other rank Keys are already strings in the AVRO schema. I dont know where the inconsistency comes from.

https://github.com/gbif/pipelines/blob/dev/sdks/models/src/main/avro/json/common-json-record.avsc#L179

Here is what we need to change to string.

https://github.com/gbif/pipelines/blob/dev/sdks/models/src/main/avro/json/common-json-record.avsc#L123

**Comment by MortenHofft** [comment]
Oh okay, odd. I just noticed the config assumes numeric and checked that our production ES mapping says
```
"kingdomKey": {
"type": "long"
},
```

**Comment by MortenHofft** [comment]
I would change it to
```
"gbifClassification_acceptedUsage_key": {
      "type": "keyword",
      "field": "occurrence.gbifClassification.acceptedUsage.guid",
    },
```

But there isn't currently an index to test this on, so I will leave it as an idea here for now

**Comment by MortenHofft** [comment]
This is a messy solution, but at least we have something working until the index gets fixed/aligned
