### ISSUE TITLE
Event sidebar - representative species images

### ISSUE THREAD

**Issue by jack-brinkman** [gbif/gbif-web#229]
I've started implementing the ability to see a representative image for each unique taxon related to an event (via its occurrences), ~in the [feature/event-taxa-images](https://github.com/gbif/gbif-web/tree/feature/event-taxa-images) branch~ (now merged with master). This builds upon the `relatedTaxa` work in #217.

This uses iNaturalist's `taxa` API endpoint, and queries using the `acceptedScientificName` field returned from the `DistinctTaxon` GraphQL type.

A few pitfalls of the current implementation:
- iNaturalist uses its own IDs to represent taxa, rather than a unique URL (`https://id.biodiversity.org.au/node/apni/2916930`), meaning we have to query via `acceptedScientificName`, which can produce inaccurate results.
- Each image component fires a separate GraphQL query to perform the taxa search rather than all images being returned from the `distinctTaxa` query.

### Screenshot

![image](https://user-images.githubusercontent.com/104949733/205212063-bd676d31-8a8d-4060-bd28-4b80cab95c24.png)

**Comment by MortenHofft** [comment]
Would it make sense to allow queries like

```gql
query {
  taxonMedia(key: String) {
    images: [Image!]!  # using the audobon core Image definition here perhaps? As that seems to be the most expressive standard for this
  }
}
```

```js
// resolver
{
  Query: {
    taxonMedia: (_, { key }, { dataSources }) =>
      dataSources.inatAPI.getImageByKey({ key }) // for now we use the inat api, but I hope we will find another solution down the line
        .then(...some mapping to the format we need for the type)
  }
}
```

And then have the resolver use inat for now, but not exposing anything inat specific in the types and queries?

**Comment by jack-brinkman** [comment]
That makes sense to me - @djtfmartin, any thoughts/concerns with using Audubon Core?

**Comment by jack-brinkman** [comment]
@MortenHofft I've just pushed a commit that changes the `Image` type to use a subset of Audubon Core terms & matches your preferred query naming (`taxonMedia` instead of `representativeImage`).

One small issue that I see is that there aren't multiple terms to provide different-sized variants of an image - i.e. iNaturalist supplies a small `square.jpg` image URL and `medium.jpg`, which is a non-square larger variant. I've added an unofficial `accessOriginalURI` property for accessing larger, full-sized variants.

**Comment by jack-brinkman** [comment]
I've now implemented the ability to view more images:

![image](https://user-images.githubusercontent.com/104949733/205826979-73e9ca7f-c051-46e9-8637-e5753fe6e6ed.png)

**Comment by jack-brinkman** [comment]
Screenshot of the above change. Note - all menu items excluding `Search GenBank` are supplied via config, and are not present by default.

![image](https://user-images.githubusercontent.com/104949733/206121936-91ab03bd-7bb6-4529-bef2-193fe9f507e2.png)

**Comment by jack-brinkman** [comment]
A species link has been added as per @djtfmartin's suggestion. `.env.json` needs to be updated to handle these links:

```js
{
  "SPECIES_URL": "https://bie.ala.org.au/species" // gbif: https://www.gbif.org/species
}
```

### Example Image

![image](https://user-images.githubusercontent.com/104949733/208337040-f8e73e6e-4658-4a67-b89b-96892462e73b.png)

**Comment by jack-brinkman** [comment]
Ah, okay - I initially opted for the `.env` configuration as it was very straightforward & I couldn't see the config value changing in the future. However, if the `ResourceLink` component is your preferred method to handle these types of links, I'll change the implementation to use them :)

**Comment by jack-brinkman** [comment]
### Updated Screenshot

![image](https://user-images.githubusercontent.com/104949733/208549402-4d1eac98-4756-4620-8286-9e388c01d667.png)

**Comment by MortenHofft** [comment]
lack of activity. Will close
