### ISSUE TITLE
Events - taxonomic coverage is misleading

### ISSUE THREAD

**Issue by djtfmartin** [gbif/gbif-web#246]
The taxonomic coverage listing on EventSidebar is misleading as it is only displaying the first 10 entries for each taxonomic rank. This was only intended to be a placeholder for something more appropriate.

Initial idea would be to replace with a chart control like:

![alt text](https://user-images.githubusercontent.com/6759267/205600208-a147a7ca-9413-4396-9e12-ced1c5066e40.png)

**Comment by MortenHofft** [comment]
lack of activity. Will close
