### ISSUE TITLE
Taxon View Component

### ISSUE THREAD

**Issue by jack-brinkman** [gbif/gbif-web#268]
This issue will track the implementation of a new taxon view component. From @djtfmartin:

> The new component should have a general purpose for natural history collections, herbaria etc.  This could be a future interface for AVH as well as supporting seed banks and may prove useful as an alternative interface for some of the hosted portals GBIF is supporting.

**Working branch:** [feature/taxon-view](https://github.com/gbif/gbif-web/tree/feature/taxon-view)

## Prerequisites
- Currently, `events-test` / `aws-events-es-2022` GraphQL server needs to be updated to include the `taxonMedia` query, which is needed for the images tab (#273)
- The ALA GraphQL `taxon` resolver needs additional work.
- The GBIF GraphQL `occurrence` resolver would need to be shared.
  - As discussed in #211, adding the `occurrence` type to the ALA resolvers means we would also have to map `dataset`, `publisher`, `collection`, etc. types
- The actual taxon search interface still needs to be designed/mocked.

Despite these prerequisites, some parts of the view can be implemented already:

### Events Tab
- A generic 'Events' tab queries events related to the selected taxon, displaying them in a table.
  - Needed to support event-based datasets (i.e. seed bank)
  - Uses `eventSearch` GraphQL query
  - Section to the right contains Extended Measurement or Fact data, in configurable groups.

### Occurrences Tab
- A generic 'Occurrences' tab queries occurrences related to the selected taxon, displaying them in a table.
  - Needed to support herbaria & natural history collections
  - Uses `occurrenceSearch` GraphQL query
  - Section to the right contains Measurement or Fact data, in configurable groups.

### Map Tab
- Shows the location of occurrences/events (depending on configuration)

### Images Tab
- Displays images of the selected taxon
- Uses the `taxonMedia` GraphQL query

### Sequences Tab
- Displays genomic data related to the current taxon.
- A new GraphQL resolver is needed for this
  - The BIE has an [unofficial API](https://bie.ala.org.au/externalSite/genbank?s=Acacia+dealbata) for scraping the first 20 GenBank records & returning them as JSON.
  - Perhaps we could write a resolver to perform a similar function for the time being

## Mockups
These mockups were designed with an independent seed bank portal app in mind, so they contain context-specific wording, etc.

Created with [Figma](https://www.figma.com/)

### Events & Occurrences Tab(s)
![image](https://user-images.githubusercontent.com/104949733/213351422-62363a6b-eff5-4817-a9e6-2cdc9e128872.png)
- The `filters` button could be replaced with the pre-existing filter buttons.

### Map Tab
![image](https://user-images.githubusercontent.com/104949733/213598332-d00b0001-aa2f-49e0-b26c-3a5ff4d6870a.png)
- Map could either query events/occurrences depending on the configuration

### Images Tab
![image](https://user-images.githubusercontent.com/104949733/213351427-f4bd75ad-ab92-40b9-b0e4-524e6f47a409.png)

**Comment by MortenHofft** [comment]
I imagine this has been implemented long ago or is no longer relevant.

We are merging hosted portal code base and gbif.org. The react-components will no longer be developed.
