### ISSUE TITLE
Expose seed bank extension in GraphQL

### ISSUE THREAD

**Issue by jack-brinkman** [gbif/gbif-web#300]
Thanks to @djtfmartin, archives containing seed bank data supplied via a draft DwCA extension are now processed (see https://github.com/gbif/pipelines/issues/862, example output [here](https://events-test.ala.org.au/es/event?apiKey=my-api-key&eventID=15312-7142)).

The data now needs to be exposed in the GraphQL service, so it can be accessed like so:

```
eventID
parentEventID
datasetTitle
// other event fields //
extensions {
  seedbank {
    seedPerGram
    formInStorage
    sampleSize
    // other seed bank properties //
  }
}
```

**Comment by djtfmartin** [comment]
this is now done after merging #300
