### ISSUE TITLE
Sign image cache URLs

### ISSUE THREAD

**Issue by MattBlissett** [gbif/gbif-web#303]
I've updated the documentation to reflect the new version of Thumbor.

https://github.com/gbif/portal16/blob/master/image_caching.md

Could we update the hosted portals to use the new API for occurrence requests (i.e. https://api.gbif.org/v1/image/cache/occurrence/2005380410/media/568639b65b65ddb9090d3d6ef1abce14) and — lower importance — sign requests for non-occurrence image requests through Thumbor.

See also https://github.com/gbif/portal16/issues/1851

**Comment by MortenHofft** [comment]
sign images on occurrence gallery view
https://github.com/gbif/gbif-web/commit/abba667073b8b5684ef6ebe8735e673c5211cdcb

**Comment by MortenHofft** [comment]
@djtfmartin We are in the process of working through our use of thumbor and sign all requests (unlike now). How would that influence you? It means that all images going through Thumbor would have to be signed (inlucing the size and other parameters) on the server. 

I imagine adding a graphql schema option to all image urls that return XS, S, M, L, XL + fit-in options.

**Comment by MortenHofft** [comment]
This have been added to graphql and the new hp stack is now using it
