### ISSUE TITLE
lib export

### ISSUE THREAD

**Issue by MortenHofft** [gbif/gbif-web#306]
https://github.com/gbif/gbif-web/commit/79410b8ff56e02583def250f1a3bd7ce33449b2b#r116020762

@djtfmartin and @jack-brinkman 
I've changed this back as it is a change that is breaking our production system. But I'm not sure what it means for you though.
We should most likely find a way to do multiple builds or configurable builds I suppose. I'm happy to discuss. But be aware that the file that I just rolled back to its previous state before the pull request might influence your systems. I should have noticed that before merging. Sorry about that.

**Comment by djtfmartin** [comment]
@MortenHofft in the interim can we include the export of `EventSearch` for now along with all the other components ? This will allow us to run a build we can use at least.

**Comment by MortenHofft** [comment]
I've changed the webpack config. It now builds an `dist/lib/ala-react-components` as well, which just includes the event search

**Comment by djtfmartin** [comment]
thanks @MortenHofft
