### ISSUE TITLE
Annotations Demo - the project page does show the correct data

### ISSUE THREAD

**Issue by jhnwllr** [gbif/gbif-web#314]
![image](https://github.com/gbif/gbif-web/assets/4245213/1a3a34b3-a8ae-45cd-9c19-480b82afd854)

**Comment by MortenHofft** [comment]
Thanks @jhnwllr Yes, we haven't done anything for the projects yet. I can change the template to not write nonsense, but adding all the editing functionalities is a bit more work than for Tuesday I imagine
