### ISSUE TITLE
IUCN status, accepted name or nor

### ISSUE THREAD

**Issue by MortenHofft** [gbif/gbif-web#320]
I'm looking into using the IUCN data for species.
I was looking at this species https://api.gbif.org/v1/species/1540460 but I'm not sure what threat status to show

The API says:
```json
  "taxonomicStatus": "SYNONYM",
  "acceptedKey": 1540459,
  "accepted": "Cheilosia means (Fabricius, 1798)",
```

The iucnRedListCategory endpoint says https://api.gbif.org/v1/species/1540460/iucnRedListCategory
```json
{
  "category": "ENDANGERED",
  "usageKey": 192020253,
  "scientificName": "Cheilosia hercyniae Loew, 1857",
  "taxonomicStatus": "ACCEPTED",
  "code": "EN"
}
```

That is already confusing (being a synonym and accepted), but I assume it means that according to IUCN it is an accepted name?

If I then go to the backbones accepted name https://api.gbif.org/v1/species/1540459/iucnRedListCategory I see that the accepted name has status `NOT_EVALUATED`.

```json
{
  "category": "NOT_EVALUATED",
  "scientificName": "Cheilosia means (Fabricius, 1798)",
  "taxonomicStatus": "ACCEPTED",
  "code": "NE"
}
```

What threat status should I show on taxon 1540460 and 1540459? 

@MattBlissett and @andrewrodrigues you have both been working with this. You can probably answer this

**Comment by MortenHofft** [comment]
Discussed offline with [andrewrodrigues](https://github.com/andrewrodrigues)

It isn't ideal that we have differing taxonomies. The best thing to do for now is to just show different threat statuses on the 2 pages. Even though GBIF consider them to be synonyms

**Comment by jhnwllr** [comment]
I computed some general stats for this problem... 

> "synonyms on the iucn redlist that have a different iucn status than their accepted name" 

~30% (3660/11096) of synonyms on the iucn redlist have a different status than their accepted name on GBIF. 

|syn iucn status        |accepted iucn status  |    n|
|:----------------------|:---------------------|----:|
|least concern          |not evaluated         | 2351|
|data deficient         |not evaluated         |  827|
|**vulnerable**             |not evaluated         |  **731**|
|**endangered**             |not evaluated         |  **667**|
|least concern          |none                  |  574|
|**critically endangered**  |not evaluated         |  **440**|
|near threatened        |not evaluated         |  317|
|data deficient         |least concern         |  278|
|vulnerable             |none                  |  158|
|vulnerable             |least concern         |  120|
|data deficient         |none                  |  101|
|endangered             |none                  |   98|
|endangered             |least concern         |   92'|
|near threatened        |none                  |   80|
|critically endangered  |none                  |   72|
|critically endangered  |least concern         |   53|
|extinct                |not evaluated         |   50|
|near threatened        |least concern         |   45|
|critically endangered  |endangered            |   27|
|data deficient         |vulnerable            |   25|

It is particularly concerning that many vulnerable, endangered, and critically endangered synonyms do not match their accepted names.

**Comment by jhnwllr** [comment]
@andrewrodrigues 

Here is how the 11,096 synonyms match to the backbone. It seems like there isn't any problems for the synonyms matching to the GBIF backbone. 

|matchType  |     n|
|:----------|-----:|
|EXACT      | 10927|
|FUZZY      |   112|
|HIGHERRANK |    57|

The higher rank matchers are mostly subspecies ect...

|rankmarker |  n|
|:----------|--:|
|infrasp.   |  9|
|sp.        |  8|
|strain     |  1|
|subsp.     | 34|
|var.       |  5|

This makes sense because in order for us to know it's a synonym, it has to match to the backbone.
