### ISSUE TITLE
getInstitutions helper function sporadically crashes graphql-api package

### ISSUE THREAD

**Issue by jack-brinkman** [gbif/gbif-web#383]
The `/grscicoll/institution` endpoint sometimes returns a 503 response, causing an exception in the `getInstitutions` function that crashes the `graphql-api` package.

### Example Log

```
AxiosError: Request failed with status code 503
    at settle (/usr/src/node_modules/axios/lib/core/settle.js:19:12)
    at IncomingMessage.handleStreamEnd (/usr/src/node_modules/axios/lib/adapters/http.js:570:11)
    at IncomingMessage.emit (node:events:525:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'ERR_BAD_RESPONSE',
  config: {
    ... more config ...
    headers: AxiosHeaders {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/1.4.0',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    method: 'get',
    url: 'https://api.gbif.org/v1/grscicoll/institution',
    data: undefined
  },
```

**Comment by MortenHofft** [comment]
@jack-brinkman and @djtfmartin 
Reminded by this issue I have changed the UI to use the new geojson endpoint https://github.com/gbif/registry/issues/494
I would like to remove the temporary endpoint `/unstable-api/map-styles/3031/institutions.geojson`. Are you using it for something else?

**Comment by jack-brinkman** [comment]
@MortenHofft - No issues from my end if you want to remove it 👍

I can do a deployment to our test environment once it's removed and see if anything breaks, but it shouldn't.

**Comment by MortenHofft** [comment]
I've removed it from master.
