### ISSUE TITLE
Loader is not showing

### ISSUE THREAD

**Issue by MortenHofft** [gbif/gbif-web#402]
There is no loader, not when changing route (home => news), nor when changing language version/route.

@danielvdm2000 I can see a loadingElement is defined, but I cannot see it being used anywhere? What am I missing. I remember you mentioned that you had this working. Is it on another branch?

**Comment by danielvdm2000** [comment]
You're correct. The `loadingElement` was not functioning in the master branch. I have now merged my branch and confirmed that it's working.

Regarding the display of a `loadingElement` when navigating from the home page to the news page, this should indeed be possible. However, there is no direct link from the home to a news page, and the `loadingElement` is only displayed during client-side navigation. It's possible you tested this using a temporary link from home to news. If that's the case, it should be functioning correctly now.

As of now, a `loadingElement` for language changes has not been defined. However, with the new code merged into the master branch, it should be possible to simply define a `loadingElement` at the root level. This element would then manage the loading process when the language is changed.

**Comment by danielvdm2000** [comment]
I have now verified that the loadingElement functions correctly on our deployed demo site.
