### ISSUE TITLE
styling known classes within a components

### ISSUE THREAD

**Issue by MortenHofft** [gbif/gbif-web#405]
@danielvdm2000 it would be great if you could answer this:

Not all css classes are generated by react and css modules. Some comes in the html from graphql or elasticsearch. Others are generated by libraries like openlayers etc. 

In other words, we need to be able to provide styling for not obfuscated classnames. And we need to be able to target them to not pollute global css space.

Example. The graphQL endpoints wraps tables from the CMS in a div with a class `gbif-table-wrapper`. I would like to be able to style that class. Not necessarily globally, but for individual pages. If I add a css module like:

```
.resourceProse {
  .gbif-table-wrapper {
    overflow-x: auto;
  }
}
```

Then both classes are randomized and do not work
```
  ._resourceProse_16d4x_1 ._gbif-table-wrapper_16d4x_3 {
    overflow-x: auto;
  }
```

I had hoped to get the weird first name, but keep the second as provided. That is the way it works in e.g. emotion css.
```
  ._resourceProse_16d4x_1 .gbif-table-wrapper {
    overflow-x: auto;
  }
```

How would I achieve this in css modules (or just this project).

**Comment by danielvdm2000** [comment]
We can do it like this:

```css
.resourceProse :global(.gbif-table-wrapper) {
  overflow-x: auto;
}
```
