### ISSUE TITLE
server side rending with css modules

### ISSUE THREAD

**Issue by MortenHofft** [gbif/gbif-web#406]
styling provided by css modules are only applied client side.
This is different from emotion that is also applied to serverside rendering. Does something similar exists for css modules please?

**Comment by MortenHofft** [comment]
I've tried to address it by making a [global css rule ](https://github.com/gbif/gbif-web/commit/9fddb96feb16cae874b3609000e6271e1f4a7915), that will work, but less ideal. I can live with it though, but the benefit of css modules is lost in this case

**Comment by danielvdm2000** [comment]
I have tested this, and it seems to be a problem only with the development server, not when using the production build. I'm not sure how to fix this on the dev server. I have had no problem with the CSS modules being loaded client-side when developing. Do you?

**Comment by danielvdm2000** [comment]
@MortenHofft can i close this issue?
