### ISSUE TITLE
Dataset search

### ISSUE THREAD

**Issue by MortenHofft** [gbif/gbif-web#419]
Existing pages
https://www.gbif.org/dataset/search
https://hp-theme.gbif-staging.org/dataset/search?

As with publisher search, the table option is nice to have. But I would like to have a card list as well. It serves smaller sites better and better allows for map thumbnails.

notice that search is broken down into 2 parts. A quick and a slow for counts.

There are many things that would be intersting to do with dataset search in the future. But for now I suggest we just focus on basic functionalities to have feature parity

**Comment by danielvdm2000** [comment]
The table has not been added for now as it not necessary for hosted portals
