### ISSUE TITLE
useQuery hook

### ISSUE THREAD

**Issue by MortenHofft** [gbif/gbif-web#426]
On the existing hosted portal components we have a useQuery hook that has served us well. Among other things it provides: 

**Caching** by using GET by IDs over posting entire queries. It provides variables as GET when they can fit into the url and will else register the variables as well.

It support **queue** names, so that e.g. dashboards can use the same queueName and avoid crashing the backends by firing many simultaneous expensive queries.

And it provides an easy wat to **cancel** requests when a component is unmounted.

I would like to see this being used on gbif-org as well. 

Having it will also make it easier to port other existing components such as dashboards

The same logic should probably be used in route loaders as these will also be used client side

**Comment by danielvdm2000** [comment]
The useQuery hook has now been implemented and is used on the occurrence search page to populate the table
