### ISSUE TITLE
Documents

### ISSUE THREAD

**Issue by MortenHofft** [gbif/gbif-web#434]
examples pages 
https://www.gbif.org/document/80536/georeferencing-best-practices
https://www.gbif.org/document/4A5CcgMpChHHaa4ySRGib/gbif-science-review-no-10

The current styling for these pages is different from the others. The reason being that they are extremely minimal for the most part.

I'm not sure what the best approach is. We can try to style it like the others and see how it works.

**Comment by danielvdm2000** [comment]
I went with keeping the "paper background look" and using the same components for title, body, ect. I think this works well with the small amount of content. The background is pure white so i had to add a lot of shadow to create contrast. We should maybe consider a light gray background all around.
