### ISSUE TITLE
tailwind purges unused classes in dev mode

### ISSUE THREAD

**Issue by MortenHofft** [gbif/gbif-web#444]
Removing unused classes in production is great, but I would like to keep them during development as I find it useful to fiddle with classes in the browser when styling components.

I see this https://v2.tailwindcss.com/docs/optimizing-for-production about purging, but setting it to false didn't seem to make a difference. They are purge either way it seemed to me

**Comment by mpitblado** [comment]
I am not sure the timeline on having a stable release out, but Just-in-Time mode would appear to enable you to use identical classes in development and production since you no longer need to worry about purging.

https://v2.tailwindcss.com/docs/just-in-time-mode

**Comment by MortenHofft** [comment]
Thanks @mpitblado 
I'm closing this issue as it is more a comvinence than anything. And it is easy to see how it could be a cause of issues. I imagine someone creating dynamic classes that then is purged in prod
