### ISSUE TITLE
demo sites throwing errors

### ISSUE THREAD

**Issue by MortenHofft** [gbif/gbif-web#457]
demo site keeps doing calls to some apparently non existing port looking for I do not know what
https://demo.gbif-dev.org:24678/

**Comment by danielvdm2000** [comment]
The demo site is currently running in development mode because NODE_ENV is set to 'development'. This causes the site to attempt to fetch code updates for enabling Hot Module Replacement. We need to set NODE_ENV to 'production'.

**Comment by danielvdm2000** [comment]
@MattBlissett can you change the environment variables to:
NODE_ENV=production
PUBLIC_GBIF_ENV=dev
