### ISSUE TITLE
Language versions

### ISSUE THREAD

**Issue by MortenHofft** [gbif/gbif-web#465]
Add tags in header about the various other languages pages are available in.

Like`<link rel="alternate" hreflang="zh-tw" href="https://www.gbif.org/zh-tw/project/CESP2022-012/improving-the-visibility-of-latin-american-natural-science-collections-through-a-global-collections-network-campaign" />` etc.

If in doubt see gbif.org for how we currently handle it.

**Comment by danielvdm2000** [comment]
I have asked Matt to provide the demo site with a new environment variable that can be used as the baseUrl. I will add the fix when he lets me know it's done.

**Comment by danielvdm2000** [comment]
I have now confirmed that this works
