### ISSUE TITLE
add option to view previews of contentful data

### ISSUE THREAD

**Issue by MortenHofft** [gbif/gbif-web#472]
On gbif.org we an provide a parameter to enable using the contentful preview API to view items in their unpublished state. This is important for editors to get a sense of what their work will look once published. 

We need to same functionality on the new site. It needs to be a predictable url param so we can template in in Contentful, but other than that there are no constraints.

**Comment by danielvdm2000** [comment]
This can now be done with a query parameter called "preview" set to true.
The preview option will be added as a header in the request to GraphQL API.
The header will be extracted into the context, where all resolvers that support preview will have access to it. This makes it a breeze to share that fact we want preview data across resolvers.
https://demo.gbif-dev.org/data-use/2NcRzaklrkf5X1mvyOvg5V/environmental-and-physiological-drivers-of-global-lichen-distribution?preview=true
