### ISSUE TITLE
review which tags we show at the bottom of contentful driven pages

### ISSUE THREAD

**Issue by MortenHofft** [gbif/gbif-web#479]
https://www.gbif-dev.org/project/BID-AF2020-094-NAC/mainstreaming-recent-species-and-ecosystem-distribution-data-into-key-biodiversity-areas-assessments-in-seychelles
vs
https://demo.gbif-dev.org/es/project/82750

apparently we do not show `Topic` tags on project pages. Perhaps never. Let us do the same on gbif.org unless told otherwise

**Comment by danielvdm2000** [comment]
The links you have provided do not lead to the same resource:
https://www.gbif-dev.org/project/82750/capacity-building-and-biodiversity-data-mobilization-for-conservation-and-policy-in-africa
vs
https://demo.gbif-dev.org/project/82750/capacity-building-and-biodiversity-data-mobilization-for-conservation-and-policy-in-africa

It appears to me that the missing `Topic` tags might be the result of a translation error, as `filters.purposes.name` translates to `Topic`. I also can't find any code in `portal16` that would exclude Topics.

Am I missing something?

Either way, I will continue to review the tags on other pages.

**Comment by MortenHofft** [comment]
The intention is for us to keep existing behaviour. If we believe it looks wrong, then change it but note it down so we can inform comms about it.

I created a test entry https://app.contentful.com/spaces/uo17ejk9rkwj/environments/dev/entries/2NcRzaklrkf5X1mvyOvg5V?focusedField=countriesOfCoverage
it looks like we show all on gbif.org, so we should just go with that on the new site as well
