### ISSUE TITLE
in local dev mode some resources will fail

### ISSUE THREAD

**Issue by MortenHofft** [gbif/gbif-web#542]
example. turn developer tools off. reload a few times. Then the menu will only show the 3 dots and not the full menu for the page. 
http://localhost:3000/project/82750/capacity-building-and-biodiversity-data-mobilization-for-conservation-and-policy-in-africa

For me it is consistently every other reload it fails.

**Comment by MortenHofft** [comment]
Doesn't even load anymore

**Comment by danielvdm2000** [comment]
The page loads again (not deployed to staging yet).

I can't reproducere the original issue. Do you (@MortenHofft ) still experience it?

**Comment by MortenHofft** [comment]
No looks fine to me.
