### ISSUE TITLE
custom page: Suggest a dataset

### ISSUE THREAD

**Issue by MortenHofft** [gbif/gbif-web#545]
yet another form based page. I suggest we make this into a custom component like for the hosted portal form That would allow us to add a bit more context prose to the page. For now we could just add it in cms dev env to test it.

It requires login in production, but we can add that logic later. For forms like these I'm tempted to not server side render them. Just to make it more of a hassle to generate spam.

https://www.gbif.org/suggest-dataset
https://github.com/gbif/data-mobilization
https://github.com/gbif/portal16/tree/master/app/controllers/api/tools/suggestDataset
https://github.com/gbif/portal16/tree/master/app/views/pages/tools/suggestDataset

**Comment by danielvdm2000** [comment]
https://demo.gbif-dev.org/suggest-dataset
