### ISSUE TITLE
custom page: become a publisher

### ISSUE THREAD

**Issue by MortenHofft** [gbif/gbif-web#546]
New publishers (also known as organizations) can register via the website. When they do there application is sent to a node for confirmation.
So this form does not go to Github, but has a separate API. That endpoint handles sending out mails, updates the registry with who confirmed etc. See https://api.gbif.org/v1/organization for example values.

https://www.gbif.org/become-a-publisher
https://github.com/gbif/portal16/tree/master/app/controllers/tools/endorsement
https://github.com/gbif/portal16/tree/master/app/views/pages/custom/becomePublisher

confirm endorsement
https://github.com/gbif/portal16/tree/master/app/views/pages/custom/confirmEndorsement
https://github.com/gbif/portal16/blob/master/app/controllers/publisher/key/publisherKey.ctrl.js#L82

You can see pending organizations at https://api.gbif-uat.org/v1/organization/pending

@MattBlissett is it correct that we do not send out emails in dev environment? I'm asking to ensure we do not spam during development.

**Comment by danielvdm2000** [comment]
https://demo.gbif-dev.org/become-a-publisher
