### ISSUE TITLE
Dataset drawer

### ISSUE THREAD

**Issue by MortenHofft** [gbif/gbif-web#550]
On the current hosted portals we use a drawer to preview and show data in some cases
https://hp-theme.gbif-staging.org/occurrence/search?view=DATASETS (click a dataset result and see the drawer sliding in)

Currently that works by adding a memory router (to avoid clashing url params). It could be nice with a test of how that would work in our new architecture

**Comment by MortenHofft** [comment]
Similar for occurrences. We open those in a drawer, but would also like to link to a url with the record on its own

**Comment by MortenHofft** [comment]
A test example could be to open occurrences in a drawer on `/occurrence/search` and in the bottom of that sidebar have a `Go to record` button in the bottom of the drawer that takes the user to the detail page `occurrence/123`

Or use `/dataset/search` and open datsets in a drawer. 

In both usecases it is also important that the urls aren't mangled by the sidebar item. E.g. tabs should no longer update the url. Instead we could use a memory router. Or another solution. Just leave the url as is if the dataset/occurrence is open in a sidebar

**Comment by danielvdm2000** [comment]
I have added Drawer component `src/components/drawer/drawer.tsx` and a StandaloneWrapper `src/components/standaloneWrapper.tsx` that can be used together to achieve this functionality.

I have also added a drawer for previewing occurrences in search.
StandaloneOccurrenceKeyPage: `src/routes/occurrence/key/standalone.tsx`
Example of the drawer/standalone combination: `src/routes/occurrence/search/occurrenceSearchPage.tsx`
