### ISSUE TITLE
Tabs only take strings not componetns

### ISSUE THREAD

**Issue by MortenHofft** [gbif/gbif-web#552]
It is useful to be able to add e.g. an icon to a tab title. Currently the components only takes strings

```
<Tabs
  links={[{ to: '.', children: 'About' }]}
/>
```

**Comment by danielvdm2000** [comment]
It looks like it is possible to provide a react element when looking a line 220 in https://github.com/gbif/gbif-web/blob/master/packages/gbif-org/src/routes/dataset/key/datasetKey.tsx
