### ISSUE TITLE
suspense error

### ISSUE THREAD

**Issue by MortenHofft** [gbif/gbif-web#566]
I get this error on the occurrence detail page
```
The server did not finish this Suspense boundary: The server used "renderToString" which does not support Suspense. If you intended for this Suspense boundary to render the fallback content on the server consider throwing an Error somewhere within the Suspense boundary. If you intended to have the server wait for the suspended component please switch to "renderToPipeableStream" which supports Suspense on the server
```

**Comment by danielvdm2000** [comment]
I don't seem to be able to reproduce in dev mode. Do you experience this with a specific occurrence?

**Comment by MortenHofft** [comment]
The lazy loaded map needs to be there of course, but other than that it can happen at any record. But it is unstable I'm afraid

**Comment by danielvdm2000** [comment]
I have created a custom suspence component called `StaticRenderSuspence` that should be used from now on to avoid this error.
