### ISSUE TITLE
Proposals for improvement of SearchKeywordsFilter UX

### ISSUE THREAD

**Issue by mpitblado** [gbif/gbif-web#572]
We have found that many users are unaware of the regex-like pattern searching in the Filter widget, and are expecting the filter widget to behave in ways that goes against its design. This issue is a proposal/request for quality of life improvements that could make the search behaviour clearer to the user.

If these sound like good ideas, I would be happy to work on a PR, however I am just unsure how I would go about creating the development environment, my current inference is that these components are delivered to the hosted portals through some sort of jekyll theme integration and that's where my knowledge ends.

## Current UX
Whether the user clicks on the filter icon beside the field name, or the filter button in the top navigation, they are presented with the popover defined in https://github.com/gbif/gbif-web/blob/cd05ea87f71d4f78c82db7d6938b3788186306ae/packages/react-components/src/widgets/Filter/types/SearchKeywordsFilter.js. This popover contains an explanation of the regex structure through `filterSupport.useWildcardPattern`, however this is only shown in the event that show suggestions is disabled, even though the functionality is accessible to the user (and behaves the same way) regardless of whether suggestions are shown. Furthermore, useful descriptions of elements (such as `*`) are not included in this tooltip.

## Proposal 1

Move `filterSupport.wildcardHelp` to be either below `filterSupport.useWildcardPattern` when suggestions are shown *or* include the `wildcardHelp` as part of `useWildcardPattern`. 

This will allow users to be informed of the regex capabilities regardless of whether they try disabling suggestions. As part of this, the `*` operation should be included in addition to `?`

*or*

## Proposal 2
Switch the default search behaviour to be a CONTAINS operation instead of a LIKE operation, and add a toggle to search by pattern.

The text search uses free text search and is more akin to what most people are familiar with for searching in my opinion. For the field specific searches, the exact match behaviour is unexpected, and leads to frustration.

**Comment by MortenHofft** [comment]
I think it sounds like a good idea to add more explicit wildcards. I can say for certainty that the wildcard option is popular. But if your user base do not like it, then I believe it can be disabled as an option. I can look into that if you prefer that version for your site

**Comment by mpitblado** [comment]
I think that what you have here is a great implementation, and perhaps I wasn't clear, our users want *more* wildcard searching, not less so don't worry about disabling it in the config!

**Comment by MortenHofft** [comment]
<img width="390" alt="Screenshot 2024-05-07 at 10 56 00" src="https://github.com/gbif/gbif-web/assets/6759267/a068714f-0b2d-41d2-af34-2f97a19bd57e">
<img width="388" alt="Screenshot 2024-05-07 at 10 55 49" src="https://github.com/gbif/gbif-web/assets/6759267/2ad27b6b-0c87-49d6-81f6-406feecc033d">

In that case I think above help texts solve it? If not, then let me know
