### ISSUE TITLE
Failing build, but works in dev

### ISSUE THREAD

**Issue by MortenHofft** [gbif/gbif-web#579]
It would be nice to align settings from development and prod to avoid errors that only appear in prod builds

```
// import { sanitize } from "isomorphic-dompurify"; only works in dev mode, not when build
```

`import { sanitize } from "isomorphic-dompurify"` works in development, but not when build. Then I get this error:
```
file:///srv/gbif-org/dist/gbif/server/entry.server.js:40
import { sanitize } from "isomorphic-dompurify";
         ^^^^^^^^
SyntaxError: Named export 'sanitize' not found. The requested module 'isomorphic-dompurify' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'isomorphic-dompurify';
const { sanitize } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:122:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:188:5)
    at async DefaultModuleLoader.import (node:internal/modules/esm/loader:228:24)
    at async file:///srv/gbif-org/gbif/server.js:48:19
```

changing it as suggested works, but will obviously create a larger bundle. 
```
import isomorphic from 'isomorphic-dompurify';
const { sanitize } = isomorphic;
```

**Comment by MortenHofft** [comment]
Same for `import { useDeepCompareEffect } from "react-use";`

**Comment by danielvdm2000** [comment]
This has now been resolved. See gbif/vite.config.ts for the solution

**Comment by danielvdm2000** [comment]
This has now been resolved. See gbif/vite.config.ts for the solution

**Comment by MortenHofft** [comment]
It would be nice if this could be made to behave the same in dev and prod. I just pushed to staging in the naive assumption that it would work because it worked locally. Can we make it break in local if we cannot make it work the same in prod

**Comment by danielvdm2000** [comment]
Vite version 5 has now aligned importing commonjs moduls across dev and prod.
https://vitejs.dev/guide/migration#ssr-externalized-modules-value-now-matches-production
