### ISSUE TITLE
ported useQuery hook does not provide errors

### ISSUE THREAD

**Issue by MortenHofft** [gbif/gbif-web#590]
When GraphQL fails, then I would expect an error to be returned in the `{data, loading, error}` response form the hook
That is not the case in the new-gbif implementation

@danielvdm2000 am I doing something wrong?

**Comment by danielvdm2000** [comment]
@MortenHofft where are you experiencing this? I just tested with `OccurrenceSummary` on http://localhost:3000/collection/03a64ffd-34d0-432c-a152-0d41d41c028f, and get the error as expected. I did make a few changes to the hook while implementing the forms, so the issue could be fixed by that

**Comment by MortenHofft** [comment]
Fair question - i cannot replicate either. closing
