### ISSUE TITLE
Unable to pass properties to tabs on detail pages

### ISSUE THREAD

**Issue by MortenHofft** [gbif/gbif-web#591]
I find it inconvenient that it isn't possible to pass properties to subpages. For example I do a slow query on a parent route. But I then have to repeat data fetching it for any subsections.

we have the `usedata from parent route` thing, but it might not be part of that, but be a subsequent client call

**Comment by danielvdm2000** [comment]
This is the build in way to handle that problem with react router dom https://reactrouter.com/en/main/hooks/use-outlet-context

What do you think of that?

**Comment by MortenHofft** [comment]
@danielvdm2000 did you ever try it? I cannot even get their basic js example working. I just get errors. I've discovered examples that do not run in the past in their docs, but in this case it might as well be related to our modifications.

**Comment by MortenHofft** [comment]
For now I'm just using regular context. It is simple to do and is less likely to be discontinued than React router's flavour of the month
