### ISSUE TITLE
Cannot view details of record

### ISSUE THREAD

**Issue by C-H-bota** [gbif/gbif-web#595]
Thank you for reporting this issue. Please describe what happened.

When I tried to get the multimedia (image of plant herbarium specimen) or record details I got the error message below. It seemed to be just this particular record, not the entire data set.

**Error message for diagnostics**
```
Error: GraphQL error: request to https://api.gbif.org/v1/dataset/040c5662-da76-4782-a48e-cdea1892d14c failed, reason: socket hang up
    at A (https://react-components.gbif.org/lib/gbif-react-components.js?v=c486aa8cdc3578b030b7a9d57318120d:16:31481)
    at https://react-components.gbif.org/lib/gbif-react-components.js?v=c486aa8cdc3578b030b7a9d57318120d:16:32472
```
Location: https://www.canadensys.net/occurrence/search?entity=2251582857&recordedBy=W.I.%20Illman&taxonKey=6363439&view=TABLE

**Comment by MortenHofft** [comment]
Thank you. For ones this is a clear error message in the diagnostics dump. An API failure on the dataset endpoint.
There isn't much we can do in these cases other than show an error and ask the user to try again. I can see our provider have had several outages on the network

We have a warning on the GBIF.org website
https://www.gbif.org/system-health
> We are seeing brief interruptions to our network, usually lasting 1-2 seconds. Our network provider is working to solve the problem.
> If you have trouble connecting to a GBIF-hosted service, please try again a minute later.
