### ISSUE TITLE
Dynamic Link do not redirect to gbif.org

### ISSUE THREAD

**Issue by MortenHofft** [gbif/gbif-web#596]
I do not see the hosted portal build ever linking to gbif.org

This comment made me think that anything not in theis list would link to gbif.org
```
},
// Uncomment this object to enable the dataset page. Otherwise it will link to GBIF.org
{
  key: 'dataset-page',
},
```

**Comment by danielvdm2000** [comment]
The key `dataset-page` has been removed from `dataset/:key` route in `src/hp/routes.tsx`. I have added the key again and tested that it works on the Hosted Portal build.
