### ISSUE TITLE
Ensure flexible routing and option to mount single pages

### ISSUE THREAD

**Issue by MortenHofft** [gbif/gbif-web#602]
A use case is a site that have multiple versions of occurrence search running under different urls with different filters.
And options to control the url of the individual occurrence records (writting custom occurrence detail pages)

**Comment by danielvdm2000** [comment]
There is now a new config option used to add multiple occurrence search pages.

An example of one extra occurrence search page:
```js
extraOccurrenceSearchPages: [
          {
            path: 'danish-occurrence/search',
            overwriteConfig: {
              occurrencePredicate: {
                type: 'and',
                predicates: [
                  {
                    type: 'equals',
                    key: 'countryCode',
                    value: 'DK',
                  },
                ],
              },
            },
          },
        ],
```

This has also been added to the hosted portal demo within the gbif-org project.
