### ISSUE TITLE
Radix navigation menu hovers is awful ui

### ISSUE THREAD

**Issue by MortenHofft** [gbif/gbif-web#633]
I find the navigation menu provided by Radix and shadcn to be awful. The menu in itself is okay, but the hover trigger is frustrating.
I see it when people use it and i experience it myself despite knowing it. 
You move those mouse up to click a menu item. But it then opens on hover. You then click it. And it will close.

It is extremely frustrating. And painful to see users try to use the site.

**Comment by danielvdm2000** [comment]
totally agree, i will see if it can be configured
