### ISSUE TITLE
Tab component is hard to reuse

### ISSUE THREAD

**Issue by MortenHofft** [gbif/gbif-web#658]
The tab component is very tied to our routing.
it would be more useful if it was abstracted into a presentation component + a behaviour component (with the tab collapsing) and interaction.

And finally that could be used with dynamic links, or whatever the user choose to insert as the li child. Could be an button with an action even (e.g. a switch). Does that make sense to you @danielvdm2000 ?

Once this is in place it should replace the tabs we use (occurrence search, occurrence details etc)

**Comment by danielvdm2000** [comment]
The tab component has been revisited to handle all our current use cases, but does still not support arbitrary values. We will implement this if the need arises in the future
