### ISSUE TITLE
Random text has appeared above menu

### ISSUE THREAD

**Issue by MortenHofft** [gbif/gbif-web#758]
Page titles show on all pages as text above the menu.

<img width="374" alt="Image" src="https://github.com/user-attachments/assets/89f20341-b6eb-421e-85b3-e10cd624886f" />

The rendered html is also invalid

Not sure what has happened, but seems we have messed something up.

@danielvdm2000 I'm not certain, but it looks like it might be https://github.com/gbif/gbif-web/commit/20f4ab8f03c8750b220c8a88d0bc5b4779ff47a7#diff-9373b9fd38fd97843b41fa25176aefe125780e1aa6573aec6f02af0cf2c9a526R77 ?
locally i get errors when checking out that commit

**Comment by danielvdm2000** [comment]
My bad, a fix is on the way
